#!/usr/bin/env python3

# This script generates `model_types` module under package `token_count`, which
# includes `MODEL_LIST` variable of a list of model identifiers, and a
# `MODEL_TYPE` type Literal constant of the same list of models.
#
# The exit code will be 2 if the generated module has been modified by this
# script, 1 if any error occurs, and 0 otherwise.
#
# To run this script, first install via `pip install -e .`.

from pathlib import Path
import itertools
from typing import Iterable
import sys

from tiktoken.model import MODEL_TO_ENCODING

this_file = Path(__file__).name


def write_identifier_list(identifiers: Iterable[str]) -> str:
    return '\n'.join(
        itertools.chain('[', (f'    "{name}",' for name in identifiers), ']'))


model_types_file = Path.cwd() / 'token_count' / 'model_types.py'
model_list_str = write_identifier_list(MODEL_TO_ENCODING)
content_to_write = ''.join([
    f'# This file is auto-generated by scripts/{this_file}.\n',
    'from typing import Literal\n',
    'from tiktoken.model import MODEL_TO_ENCODING\n',
    'MODEL_LIST = list(MODEL_TO_ENCODING)\n',
    f'MODEL_TYPE = Literal{model_list_str}\n',
])
with open(model_types_file, 'r+', encoding='utf-8') as infile:
    old_content = infile.read()
    if old_content != content_to_write:
        infile.seek(0)
        infile.truncate(0)
        infile.write(content_to_write)
if old_content != content_to_write:
    sys.exit(2)
